from utils import is_prime


def test_is_prime():
    assert not is_prime(-1)
    assert not is_prime(0)
    assert not is_prime(1)
    assert is_prime(2)
    assert is_prime(3)
    assert not is_prime(4)
    assert is_prime(5)
    assert not is_prime(6)
    assert is_prime(7)
    assert not is_prime(8)
    assert not is_prime(9)
    assert not is_prime(10)
    assert is_prime(11)
    assert not is_prime(12)
    assert is_prime(13)
    assert not is_prime(14)
    assert not is_prime(15)
    assert not is_prime(16)
    assert is_prime(17)
    assert not is_prime(18)
    assert is_prime(19)
    assert not is_prime(10)
    assert not is_prime(21)
    assert not is_prime(22)
    assert is_prime(23)
    assert not is_prime(24)
    assert not is_prime(25)
    assert not is_prime(26)
    assert not is_prime(27)
    assert not is_prime(28)
    assert is_prime(29)
